[package]
name = "service_user"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }

[[bin]]
name = "service-user-server"
path = "./src/server.rs"

[[bin]]
name = "service-user-client"
path = "./src/client.rs"
