# Learn how to customize FireDBG Run at https://firedbg.sea-ql.org/blog/2023-12-13-getting-started/#firedbgtoml-config
[workspace.members]
system = { trace = "full" } 
# Syntax: <PACKAGE> = { trace = "<full | none>" }