//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

/// PROFILE TABLE
pub use super::profile::Entity as Profile;
pub use super::profile::ActiveModel as ProfileActiveModel;
pub use super::profile::Model as ProfileModel;
pub use super::profile::Column as ProfileColumn;
/// USER TABLE
pub use super::user::Entity as User;
pub use super::user::ActiveModel as UserActiveModel;
pub use super::user::Model as UserModel;
pub use super::user::Column as UserColumn;