[package]
name = "service_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }

[[bin]]
name = "service-auth-server"
path = "./src/server.rs"

[[bin]]
name = "service-auth-client"
path = "./src/client.rs"